version: '3'

services:
  symfony_monolith:
    image: nginx:latest
    ports:
      - '8000:80'
    volumes:
      - './symfony-monolith:/app'
      - './.docker/local/symfony_monolith/symfony_monolith.conf:/etc/nginx/conf.d/symfony_monolith.conf'
    depends_on:
      - fpm
    links:
      - fpm
    container_name: 'component-architecture-monolith-nginx'

  fpm:
    image: php:7.4-component-architecture
    build:
      context: './.docker/local/symfony_monolith'
      dockerfile: fpm.Dockerfile
    links:
      - master_db
    volumes:
      - './symfony-monolith:/app'
    container_name: 'component-architecture-monolith-fpm'

  master_db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_ROOT_PASSWORD
      - MYSQL_DATABASE=component
    volumes:
      - mysql_master:/var/lib/mysql
    container_name: 'component-architecture-master-db'

  category:
    image: go:component-architecture
    build:
      context: './'
      dockerfile: './.docker/local/category-microservice/Dockerfile'
    links:
      - master_db
    depends_on:
      - master_db
    ports:
      - '8001:8080'
    container_name: 'component-architecture-category'

  rabbitMQ:
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq_admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - '15672:15672'
    container_name: 'component-architecture-rabbitmq'

volumes:
  mysql_master:
    driver: local
  mysql_projection:
    driver: local
