parameters:
    default_communication_rabbit_mq_exchange: 'microservice-communication-exchange'
    default_monolith_queue_rabbit_mq_exchange: 'monolith-exchange'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Component\Book\UI\Controller\:
        resource: '../src/Component/Book/UI/Controller'
        tags: ['controller.service_arguments']

    Symfony\Component\String\Slugger\AsciiSlugger:
        class: Symfony\Component\String\Slugger\AsciiSlugger

    # Communication

    sync.http.category.communication:
        class: App\Infrastructure\Microservices\Communication\Sync\HttpCommunication
        public: true
        autowire: false
        arguments:
            - '@http_client'
            - '%env(resolve:CATEGORY_MICROSERVICE_URL)%'
            - 1

    # Queue

    async.rabbit_mq.default.queue_publisher:
        class: App\Infrastructure\Queue\RabbitMQQueuePublisher
        public: true
        autowire: false
        arguments:
            - '@PhpAmqpLib\Connection\AMQPStreamConnection'
            - '%default_monolith_queue_rabbit_mq_exchange%'
            - 1

    # Event listener

    # Event publisher

    async.rabbit_mq.default.event_publisher:
        class: App\Infrastructure\EventDispatcher\EventPublisher\AsyncEventPublisher
        public: true
        autowire: false
        arguments:
            - '@async.rabbit_mq.default.queue_publisher'
            - '@Symfony\Component\Serializer\SerializerInterface'

    sync.symfony.event_publisher:
        class: App\Infrastructure\EventDispatcher\EventPublisher\SyncSymfonyEventPublisher

    # Event dispatcher

    create.book.event_dispatcher:
        class: App\Infrastructure\EventDispatcher\EventDispatcher
        public: true
        autowire: false
        arguments:
            - '@async.rabbit_mq.default.event_publisher'

    sync.symfony.event_dispatcher:
        class: App\Infrastructure\EventDispatcher\EventDispatcher
        public: true
        autowire: false
        arguments:
            - '@sync.symfony.event_publisher'

    # Use Case

    App\Component\Book\Core\UseCase\CreateBookApplicationService:
        class: App\Component\Book\Core\UseCase\CreateBookApplicationService
        public: true
        autowire: false
        arguments:
            - '@App\Component\Book\Core\Factory\BookFactory'
            - '@App\Component\Book\Core\Repository\BookRepository'
            - '@App\Infrastructure\UnityOfWork\UnityOfWork'
            - '@create.book.event_dispatcher'

    # API

    App\Component\Category\API\CategoryApiInterface:
        class: App\Component\Category\API\CategoryApi
        autowire: false
        public: true
        arguments:
            - '@sync.http.category.communication'

    # Other

    PhpAmqpLib\Connection\AMQPStreamConnection:
        class: PhpAmqpLib\Connection\AMQPStreamConnection
        autowire: false
        public: true
        arguments:
            - '%env(resolve:RABBITMQ_HOST)%'
            - '%env(resolve:RABBITMQ_PORT)%'
            - '%env(resolve:RABBITMQ_USER)%'
            - '%env(resolve:RABBITMQ_PASS)%'
