parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Component\Book\UI\Controller\:
        resource: '../src/Component/Book/UI/Controller'
        tags: ['controller.service_arguments']

    Symfony\Component\String\Slugger\AsciiSlugger:
        class: Symfony\Component\String\Slugger\AsciiSlugger