doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Component\Book\Core\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Component/Book/Core/Entity'
                prefix: 'App\Component\Book\Core\Entity'
                alias: App
